# Generated by Django 5.0.4 on 2026-04-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('total_listen_time', models.IntegerField(default=0)),
                ('songs_heard_count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discord_users',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpage_url', models.URLField(db_index=True, max_length=512, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('duration', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('first_played', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='ListenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(db_index=True, max_length=64)),
                ('duration_listened', models.IntegerField(default=0)),
                ('completion_ratio', models.FloatField(default=0.0)),
                ('reason', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('stopped', 'Stopped')], default='completed', max_length=32)),
                ('listened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_events', to='recommendations.discorduser')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_events', to='recommendations.song')),
            ],
            options={
                'db_table': 'listen_events',
                'indexes': [models.Index(fields=['user', 'guild_id'], name='listen_even_user_id_806693_idx'), models.Index(fields=['song', 'guild_id'], name='listen_even_song_id_5c995c_idx'), models.Index(fields=['listened_at'], name='listen_even_listene_17714e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuildSongStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(db_index=True, max_length=64)),
                ('play_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('unique_listeners', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.song')),
            ],
            options={
                'db_table': 'guild_song_stats',
                'indexes': [models.Index(fields=['guild_id', 'play_count'], name='guild_song__guild_i_fcc05c_idx'), models.Index(fields=['guild_id', 'last_played'], name='guild_song__guild_i_107b0d_idx')],
                'unique_together': {('guild_id', 'song')},
            },
        ),
    ]
