global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "development"

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "elixir"
    static_configs:
      - targets: ["elixir:4000"]
    metrics_path: "/metrics"

  - job_name: "django"
    static_configs:
      - targets: ["django:8000"]
    metrics_path: "/metrics"

  - job_name: "celery"
    static_configs:
      - target: ["celery:9808"]
    metrics_path: "/metrics"